# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 2026.1.post1
  python_check_max: "3.14"

package:
  name: pytz
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pytz/pytz-${{ version }}.tar.gz
  sha256: 3378dde6a0c3d26719182142c56e60c7f9af7e968076f31aae569d72a0358ee1

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports: pytz
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - requirements:
      run:
        - pytest-cov
        - python ${{ python_min }}.*
    script:
      - coverage run --source=pytz --branch -m pytest -vv --tb=long --color=yes --pyargs pytz
      - coverage report --show-missing --skip-covered --fail-under=100

about:
  license: MIT
  license_file: LICENSE.txt
  summary: World timezone definitions, modern and historical.
  description: |
    pytz brings the Olson tz database into Python. This library allows
    accurate and cross platform timezone calculations using Python 2.4 or
    higher. It also solves the issue of ambiguous times at the end of daylight
    saving time.
  homepage: https://pypi.org/project/pytz
  repository: https://github.com/stub42/pytz
  documentation: https://pythonhosted.org/pytz

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
